### ISSUE TITLE
No Procfile?

### ISSUE THREAD

**Issue by tmcw** [heroku/button-sample#3]
Does the presence of `app.json` make Procfile unnecessary? Copying this repo leads to a project with no dynos running, and scaling up gives me

```
~/tmp/turf-server-example〉heroku ps:scale web=1
Scaling dynos... failed
 !    No such process type web defined in Procfile.
```

**Comment by jonmountjoy** [comment]
Hi

I can't reproduce your problem @tmcw - how did you deploy the app?  Using Heroku Button, or did you push to some existing app you already had? 

By default, Heroku will auto-create a Procfile if it doesn't exist (see [documentation](https://devcenter.heroku.com/articles/nodejs-support#default-web-process-type)).  If you push from the command line you'll see something like this:

```
remote:
remote: -----> Checking startup method
remote:        No Procfile; Adding 'web: npm start' to new Procfile
remote:
```

**Comment by zeke** [comment]
The node buildpack doesn't require a `Procfile`. If no `Procfile` is found, one will be created using the value of `scripts.start` in package.json.

https://github.com/heroku/heroku-buildpack-nodejs/blob/197845da93ba74e15440b9bd9ee121a05bf8238c/lib/build.sh#L195-L211

**Comment by tmcw** [comment]
Gotcha, must've been a temporary issue.
